export const ATURAN = [
  {
    no: 1,
    umur: "Muda",
    berat: "Sangat kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 2,
    umur: "Muda",
    berat: "Sangat kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 3,
    umur: "Muda",
    berat: "Sangat kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 4,
    umur: "Muda",
    berat: "Sangat kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 5,
    umur: "Muda",
    berat: "Sangat kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 6,
    umur: "Muda",
    berat: "Sangat kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 7,
    umur: "Muda",
    berat: "Sangat kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 8,
    umur: "Muda",
    berat: "Sangat kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 9,
    umur: "Muda",
    berat: "Sangat kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Banyak",
  },
  {
    no: 10,
    umur: "Muda",
    berat: "Sangat kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Banyak",
  },
  {
    no: 11,
    umur: "Muda",
    berat: "Kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 12,
    umur: "Muda",
    berat: "Kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 13,
    umur: "Muda",
    berat: "Kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 14,
    umur: "Muda",
    berat: "Kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 15,
    umur: "Muda",
    berat: "Kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 16,
    umur: "Muda",
    berat: "Kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 17,
    umur: "Muda",
    berat: "Kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Banyak",
  },
  {
    no: 18,
    umur: "Muda",
    berat: "Kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Banyak",
  },
  {
    no: 19,
    umur: "Muda",
    berat: "Kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Banyak",
  },
  {
    no: 20,
    umur: "Muda",
    berat: "Kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Banyak",
  },
  {
    no: 21,
    umur: "Muda",
    berat: "Normal",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 22,
    umur: "Muda",
    berat: "Normal",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 23,
    umur: "Muda",
    berat: "Normal",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 24,
    umur: "Muda",
    berat: "Normal",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 25,
    umur: "Muda",
    berat: "Normal",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Banyak",
  },
  {
    no: 26,
    umur: "Muda",
    berat: "Normal",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Banyak",
  },
  {
    no: 27,
    umur: "Muda",
    berat: "Normal",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Banyak",
  },
  {
    no: 28,
    umur: "Muda",
    berat: "Normal",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Banyak",
  },
  {
    no: 29,
    umur: "Muda",
    berat: "Normal",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 30,
    umur: "Muda",
    berat: "Normal",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 31,
    umur: "Muda",
    berat: "Gemuk",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 32,
    umur: "Muda",
    berat: "Gemuk",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 33,
    umur: "Muda",
    berat: "Gemuk",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 34,
    umur: "Muda",
    berat: "Gemuk",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 35,
    umur: "Muda",
    berat: "Gemuk",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Banyak",
  },
  {
    no: 36,
    umur: "Muda",
    berat: "Gemuk",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Banyak",
  },
  {
    no: 37,
    umur: "Muda",
    berat: "Gemuk",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 38,
    umur: "Muda",
    berat: "Gemuk",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 39,
    umur: "Muda",
    berat: "Gemuk",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 40,
    umur: "Muda",
    berat: "Gemuk",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 41,
    umur: "Muda",
    berat: "Obesitas",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 42,
    umur: "Muda",
    berat: "Obesitas",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 43,
    umur: "Muda",
    berat: "Obesitas",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 44,
    umur: "Muda",
    berat: "Obesitas",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 45,
    umur: "Muda",
    berat: "Obesitas",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 46,
    umur: "Muda",
    berat: "Obesitas",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 47,
    umur: "Muda",
    berat: "Obesitas",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 48,
    umur: "Muda",
    berat: "Obesitas",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 49,
    umur: "Muda",
    berat: "Obesitas",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 50,
    umur: "Muda",
    berat: "Obesitas",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 51,
    umur: "Parobaya",
    berat: "Sangat kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 52,
    umur: "Parobaya",
    berat: "Sangat kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 53,
    umur: "Parobaya",
    berat: "Sangat kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 54,
    umur: "Parobaya",
    berat: "Sangat kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Banyak",
  },
  {
    no: 55,
    umur: "Parobaya",
    berat: "Sangat kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Banyak",
  },
  {
    no: 56,
    umur: "Parobaya",
    berat: "Sangat kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Banyak",
  },
  {
    no: 57,
    umur: "Parobaya",
    berat: "Sangat kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Banyak",
  },
  {
    no: 58,
    umur: "Parobaya",
    berat: "Sangat kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Banyak",
  },
  {
    no: 59,
    umur: "Parobaya",
    berat: "Sangat kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Banyak",
  },
  {
    no: 60,
    umur: "Parobaya",
    berat: "Sangat kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Banyak",
  },
  {
    no: 61,
    umur: "Parobaya",
    berat: "Kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 62,
    umur: "Parobaya",
    berat: "Kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 63,
    umur: "Parobaya",
    berat: "Kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 64,
    umur: "Parobaya",
    berat: "Kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 65,
    umur: "Parobaya",
    berat: "Kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 66,
    umur: "Parobaya",
    berat: "Kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 67,
    umur: "Parobaya",
    berat: "Kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 68,
    umur: "Parobaya",
    berat: "Kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 69,
    umur: "Parobaya",
    berat: "Kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 70,
    umur: "Parobaya",
    berat: "Kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 71,
    umur: "Parobaya",
    berat: "Normal",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 72,
    umur: "Parobaya",
    berat: "Normal",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 73,
    umur: "Parobaya",
    berat: "Normal",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 74,
    umur: "Parobaya",
    berat: "Normal",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 75,
    umur: "Parobaya",
    berat: "Normal",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 76,
    umur: "Parobaya",
    berat: "Normal",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 77,
    umur: "Parobaya",
    berat: "Normal",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 78,
    umur: "Parobaya",
    berat: "Normal",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 79,
    umur: "Parobaya",
    berat: "Normal",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 80,
    umur: "Parobaya",
    berat: "Normal",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 81,
    umur: "Parobaya",
    berat: "Gemuk",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 82,
    umur: "Parobaya",
    berat: "Gemuk",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 83,
    umur: "Parobaya",
    berat: "Gemuk",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 84,
    umur: "Parobaya",
    berat: "Gemuk",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 85,
    umur: "Parobaya",
    berat: "Gemuk",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 86,
    umur: "Parobaya",
    berat: "Gemuk",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 87,
    umur: "Parobaya",
    berat: "Gemuk",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 88,
    umur: "Parobaya",
    berat: "Gemuk",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 89,
    umur: "Parobaya",
    berat: "Gemuk",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 90,
    umur: "Parobaya",
    berat: "Gemuk",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 91,
    umur: "Parobaya",
    berat: "Obesitas",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 92,
    umur: "Parobaya",
    berat: "Obesitas",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 93,
    umur: "Parobaya",
    berat: "Obesitas",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 94,
    umur: "Parobaya",
    berat: "Obesitas",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 95,
    umur: "Parobaya",
    berat: "Obesitas",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 96,
    umur: "Parobaya",
    berat: "Obesitas",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 97,
    umur: "Parobaya",
    berat: "Obesitas",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 98,
    umur: "Parobaya",
    berat: "Obesitas",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 99,
    umur: "Parobaya",
    berat: "Obesitas",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 100,
    umur: "Parobaya",
    berat: "Obesitas",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 101,
    umur: "Tua",
    berat: "Sangat kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 102,
    umur: "Tua",
    berat: "Sangat kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 103,
    umur: "Tua",
    berat: "Sangat kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 104,
    umur: "Tua",
    berat: "Sangat kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 105,
    umur: "Tua",
    berat: "Sangat kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 106,
    umur: "Tua",
    berat: "Sangat kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 107,
    umur: "Tua",
    berat: "Sangat kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 108,
    umur: "Tua",
    berat: "Sangat kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 109,
    umur: "Tua",
    berat: "Sangat kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 110,
    umur: "Tua",
    berat: "Sangat kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 111,
    umur: "Tua",
    berat: "Kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 112,
    umur: "Tua",
    berat: "Kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 113,
    umur: "Tua",
    berat: "Kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 114,
    umur: "Tua",
    berat: "Kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 115,
    umur: "Tua",
    berat: "Kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 116,
    umur: "Tua",
    berat: "Kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 117,
    umur: "Tua",
    berat: "Kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 118,
    umur: "Tua",
    berat: "Kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 119,
    umur: "Tua",
    berat: "Kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 120,
    umur: "Tua",
    berat: "Kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 121,
    umur: "Tua",
    berat: "Normal",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 122,
    umur: "Tua",
    berat: "Normal",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 123,
    umur: "Tua",
    berat: "Normal",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 124,
    umur: "Tua",
    berat: "Normal",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 125,
    umur: "Tua",
    berat: "Normal",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 126,
    umur: "Tua",
    berat: "Normal",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 127,
    umur: "Tua",
    berat: "Normal",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 128,
    umur: "Tua",
    berat: "Normal",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 129,
    umur: "Tua",
    berat: "Normal",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 130,
    umur: "Tua",
    berat: "Normal",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 131,
    umur: "Tua",
    berat: "Gemuk",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 132,
    umur: "Tua",
    berat: "Gemuk",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 133,
    umur: "Tua",
    berat: "Gemuk",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 134,
    umur: "Tua",
    berat: "Gemuk",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 135,
    umur: "Tua",
    berat: "Gemuk",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 136,
    umur: "Tua",
    berat: "Gemuk",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 137,
    umur: "Tua",
    berat: "Gemuk",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 138,
    umur: "Tua",
    berat: "Gemuk",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 139,
    umur: "Tua",
    berat: "Gemuk",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 140,
    umur: "Tua",
    berat: "Gemuk",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 141,
    umur: "Tua",
    berat: "Obesitas",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 142,
    umur: "Tua",
    berat: "Obesitas",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 143,
    umur: "Tua",
    berat: "Obesitas",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 144,
    umur: "Tua",
    berat: "Obesitas",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 145,
    umur: "Tua",
    berat: "Obesitas",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 146,
    umur: "Tua",
    berat: "Obesitas",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 147,
    umur: "Tua",
    berat: "Obesitas",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 148,
    umur: "Tua",
    berat: "Obesitas",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 149,
    umur: "Tua",
    berat: "Obesitas",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 150,
    umur: "Tua",
    berat: "Obesitas",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 151,
    umur: "Sangat Tua",
    berat: "Sangat kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 152,
    umur: "Sangat Tua",
    berat: "Sangat kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 153,
    umur: "Sangat Tua",
    berat: "Sangat kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 154,
    umur: "Sangat Tua",
    berat: "Sangat kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 155,
    umur: "Sangat Tua",
    berat: "Sangat kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 156,
    umur: "Sangat Tua",
    berat: "Sangat kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 157,
    umur: "Sangat Tua",
    berat: "Sangat kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 158,
    umur: "Sangat Tua",
    berat: "Sangat kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 159,
    umur: "Sangat Tua",
    berat: "Sangat kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 160,
    umur: "Sangat Tua",
    berat: "Sangat kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 161,
    umur: "Sangat Tua",
    berat: "Kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 162,
    umur: "Sangat Tua",
    berat: "Kurus",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 163,
    umur: "Sangat Tua",
    berat: "Kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 164,
    umur: "Sangat Tua",
    berat: "Kurus",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 165,
    umur: "Sangat Tua",
    berat: "Kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 166,
    umur: "Sangat Tua",
    berat: "Kurus",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 167,
    umur: "Sangat Tua",
    berat: "Kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 168,
    umur: "Sangat Tua",
    berat: "Kurus",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 169,
    umur: "Sangat Tua",
    berat: "Kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 170,
    umur: "Sangat Tua",
    berat: "Kurus",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 171,
    umur: "Sangat Tua",
    berat: "Normal",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 172,
    umur: "Sangat Tua",
    berat: "Normal",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 173,
    umur: "Sangat Tua",
    berat: "Normal",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 174,
    umur: "Sangat Tua",
    berat: "Normal",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 175,
    umur: "Sangat Tua",
    berat: "Normal",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 176,
    umur: "Sangat Tua",
    berat: "Normal",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 177,
    umur: "Sangat Tua",
    berat: "Normal",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 178,
    umur: "Sangat Tua",
    berat: "Normal",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 179,
    umur: "Sangat Tua",
    berat: "Normal",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 180,
    umur: "Sangat Tua",
    berat: "Normal",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 181,
    umur: "Sangat Tua",
    berat: "Gemuk",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 182,
    umur: "Sangat Tua",
    berat: "Gemuk",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 183,
    umur: "Sangat Tua",
    berat: "Gemuk",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 184,
    umur: "Sangat Tua",
    berat: "Gemuk",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 185,
    umur: "Sangat Tua",
    berat: "Gemuk",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 186,
    umur: "Sangat Tua",
    berat: "Gemuk",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 187,
    umur: "Sangat Tua",
    berat: "Gemuk",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Banyak",
  },
  {
    no: 188,
    umur: "Sangat Tua",
    berat: "Gemuk",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Banyak",
  },
  {
    no: 189,
    umur: "Sangat Tua",
    berat: "Gemuk",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Banyak",
  },
  {
    no: 190,
    umur: "Sangat Tua",
    berat: "Gemuk",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Banyak",
  },
  {
    no: 191,
    umur: "Sangat Tua",
    berat: "Obesitas",
    aktivitas: "Istirahat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedikit",
  },
  {
    no: 192,
    umur: "Sangat Tua",
    berat: "Obesitas",
    aktivitas: "Istirahat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedikit",
  },
  {
    no: 193,
    umur: "Sangat Tua",
    berat: "Obesitas",
    aktivitas: "Ringan",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 194,
    umur: "Sangat Tua",
    berat: "Obesitas",
    aktivitas: "Ringan",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 195,
    umur: "Sangat Tua",
    berat: "Obesitas",
    aktivitas: "Sedang",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Sedang",
  },
  {
    no: 196,
    umur: "Sangat Tua",
    berat: "Obesitas",
    aktivitas: "Sedang",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Sedang",
  },
  {
    no: 197,
    umur: "Sangat Tua",
    berat: "Obesitas",
    aktivitas: "Berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Banyak",
  },
  {
    no: 198,
    umur: "Sangat Tua",
    berat: "Obesitas",
    aktivitas: "Berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Banyak",
  },
  {
    no: 199,
    umur: "Sangat Tua",
    berat: "Obesitas",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Laki-laki",
    kalori_harian: "Banyak",
  },
  {
    no: 200,
    umur: "Sangat Tua",
    berat: "Obesitas",
    aktivitas: "Sangat berat",
    jenis_kelamin: "Perempuan",
    kalori_harian: "Banyak",
  },
];
