export const PEKERJAAN = [
  { nama_pekerjaan: "Pekerjaan Kantoran", aktivitas: "ringan" },
  { nama_pekerjaan: "Guru", aktivitas: "sedang" },
  { nama_pekerjaan: "Dokter", aktivitas: "berat" },
  { nama_pekerjaan: "Pegawai Restoran", aktivitas: "sedang" },
  { nama_pekerjaan: "Petugas Kebersihan", aktivitas: "ringan" },
  { nama_pekerjaan: "Pegawai Konstruksi", aktivitas: "berat" },
  { nama_pekerjaan: "Desainer Grafis", aktivitas: "ringan" },
  { nama_pekerjaan: "Programmer", aktivitas: "ringan" },
  { nama_pekerjaan: "Penulis", aktivitas: "ringan" },
  { nama_pekerjaan: "Koki", aktivitas: "sedang" },
  { nama_pekerjaan: "Pramugari", aktivitas: "sedang" },
  { nama_pekerjaan: "Petani", aktivitas: "berat" },
  { nama_pekerjaan: "Tukang Las", aktivitas: "berat" },
  { nama_pekerjaan: "Polisi", aktivitas: "sedang" },
  { nama_pekerjaan: "Montir", aktivitas: "sedang" },
  { nama_pekerjaan: "Pekerja Pabrik", aktivitas: "berat" },
  { nama_pekerjaan: "Penjahit", aktivitas: "ringan" },
  { nama_pekerjaan: "Pegawai Bank", aktivitas: "ringan" },
  { nama_pekerjaan: "Insinyur", aktivitas: "ringan" },
  { nama_pekerjaan: "Arsitek", aktivitas: "ringan" },
  { nama_pekerjaan: "Aktor/Aktris", aktivitas: "ringan" },
  { nama_pekerjaan: "Seniman", aktivitas: "ringan" },
  { nama_pekerjaan: "Musisi", aktivitas: "ringan" },
  { nama_pekerjaan: "Penari", aktivitas: "sedang" },
  { nama_pekerjaan: "Atlet", aktivitas: "berat" },
  { nama_pekerjaan: "Pelaut", aktivitas: "sedang" },
  { nama_pekerjaan: "Pengacara", aktivitas: "ringan" },
  { nama_pekerjaan: "Wartawan", aktivitas: "ringan" },
  { nama_pekerjaan: "Peneliti", aktivitas: "ringan" },
  { nama_pekerjaan: "Fotografer", aktivitas: "ringan" },
  { nama_pekerjaan: "Diplomat", aktivitas: "ringan" },
  { nama_pekerjaan: "Perawat", aktivitas: "sedang" },
  { nama_pekerjaan: "Apoteker", aktivitas: "ringan" },
  { nama_pekerjaan: "Psikolog", aktivitas: "ringan" },
  { nama_pekerjaan: "Ahli Gizi", aktivitas: "ringan" },
  { nama_pekerjaan: "Terapis", aktivitas: "sedang" },
  { nama_pekerjaan: "Pengajar", aktivitas: "sedang" },
  { nama_pekerjaan: "Peneliti Medis", aktivitas: "berat" },
  { nama_pekerjaan: "Pengusaha", aktivitas: "sedang" },
  { nama_pekerjaan: "Marketing", aktivitas: "ringan" },
  { nama_pekerjaan: "Manajer", aktivitas: "ringan" },
  { nama_pekerjaan: "Pilot", aktivitas: "sedang" },
  { nama_pekerjaan: "Sipir", aktivitas: "berat" },
  { nama_pekerjaan: "Pramugara", aktivitas: "sedang" },
  { nama_pekerjaan: "Bartender", aktivitas: "sedang" },
  { nama_pekerjaan: "Perawat Hewan", aktivitas: "ringan" },
  { nama_pekerjaan: "Teknisi Komputer", aktivitas: "ringan" },
  { nama_pekerjaan: "Supir", aktivitas: "sedang" },
  { nama_pekerjaan: "Satpam", aktivitas: "sedang" },
  { nama_pekerjaan: "Akuntan", aktivitas: "ringan" },
  { nama_pekerjaan: "Agen Asuransi", aktivitas: "ringan" },
  { nama_pekerjaan: "Pegawai Kantor Pos", aktivitas: "ringan" },
  { nama_pekerjaan: "Pegawai Imigrasi", aktivitas: "ringan" },
  { nama_pekerjaan: "Pelatih Olahraga", aktivitas: "ringan" },
  { nama_pekerjaan: "Karyawan Toko", aktivitas: "ringan" },
  { nama_pekerjaan: "Pegawai Keuangan", aktivitas: "ringan" },
  { nama_pekerjaan: "Pegawai Hotel", aktivitas: "sedang" },
  { nama_pekerjaan: "Pegawai Travel", aktivitas: "ringan" },
  { nama_pekerjaan: "Konsultan Keuangan", aktivitas: "ringan" },
  { nama_pekerjaan: "Pelukis", aktivitas: "ringan" },
  { nama_pekerjaan: "Koreografer", aktivitas: "sedang" },
  { nama_pekerjaan: "Pembawa Acara", aktivitas: "ringan" },
  { nama_pekerjaan: "Asisten Rumah Tangga", aktivitas: "sedang" },
  { nama_pekerjaan: "Juragan Kapal", aktivitas: "berat" },
  { nama_pekerjaan: "Pegawai Administrasi", aktivitas: "ringan" },
  { nama_pekerjaan: "Petugas Bank", aktivitas: "ringan" },
  { nama_pekerjaan: "Pelayan Restoran", aktivitas: "ringan" },
  { nama_pekerjaan: "Pekerja Konstruksi", aktivitas: "berat" },
  { nama_pekerjaan: "Petugas Parkir", aktivitas: "ringan" },
  { nama_pekerjaan: "Pegawai Jasa Pengiriman", aktivitas: "ringan" },
  { nama_pekerjaan: "Konsultan Bisnis", aktivitas: "ringan" },
  { nama_pekerjaan: "Penulis Naskah", aktivitas: "ringan" },
  { nama_pekerjaan: "Editor", aktivitas: "ringan" },
];
