export const PEKERJAAN = [
  { nama_pekerjaan: "Pekerjaan Kantoran", kategori: "ringan" },
  { nama_pekerjaan: "Guru", kategori: "sedang" },
  { nama_pekerjaan: "Dokter", kategori: "berat" },
  { nama_pekerjaan: "Pegawai Restoran", kategori: "sedang" },
  { nama_pekerjaan: "Petugas Kebersihan", kategori: "ringan" },
  { nama_pekerjaan: "Pegawai Konstruksi", kategori: "berat" },
  { nama_pekerjaan: "Desainer Grafis", kategori: "ringan" },
  { nama_pekerjaan: "Programmer", kategori: "ringan" },
  { nama_pekerjaan: "Penulis", kategori: "ringan" },
  { nama_pekerjaan: "Koki", kategori: "sedang" },
  { nama_pekerjaan: "Pramugari", kategori: "sedang" },
  { nama_pekerjaan: "Petani", kategori: "berat" },
  { nama_pekerjaan: "Tukang Las", kategori: "berat" },
  { nama_pekerjaan: "Polisi", kategori: "sedang" },
  { nama_pekerjaan: "Montir", kategori: "sedang" },
  { nama_pekerjaan: "Pekerja Pabrik", kategori: "berat" },
  { nama_pekerjaan: "Penjahit", kategori: "ringan" },
  { nama_pekerjaan: "Pegawai Bank", kategori: "ringan" },
  { nama_pekerjaan: "Insinyur", kategori: "ringan" },
  { nama_pekerjaan: "Arsitek", kategori: "ringan" },
  { nama_pekerjaan: "Aktor/Aktris", kategori: "ringan" },
  { nama_pekerjaan: "Seniman", kategori: "ringan" },
  { nama_pekerjaan: "Musisi", kategori: "ringan" },
  { nama_pekerjaan: "Penari", kategori: "sedang" },
  { nama_pekerjaan: "Atlet", kategori: "berat" },
  { nama_pekerjaan: "Pelaut", kategori: "sedang" },
  { nama_pekerjaan: "Pengacara", kategori: "ringan" },
  { nama_pekerjaan: "Wartawan", kategori: "ringan" },
  { nama_pekerjaan: "Peneliti", kategori: "ringan" },
  { nama_pekerjaan: "Fotografer", kategori: "ringan" },
  { nama_pekerjaan: "Diplomat", kategori: "ringan" },
  { nama_pekerjaan: "Perawat", kategori: "sedang" },
  { nama_pekerjaan: "Apoteker", kategori: "ringan" },
  { nama_pekerjaan: "Psikolog", kategori: "ringan" },
  { nama_pekerjaan: "Ahli Gizi", kategori: "ringan" },
  { nama_pekerjaan: "Terapis", kategori: "sedang" },
  { nama_pekerjaan: "Pengajar", kategori: "sedang" },
  { nama_pekerjaan: "Peneliti Medis", kategori: "berat" },
  { nama_pekerjaan: "Pengusaha", kategori: "sedang" },
  { nama_pekerjaan: "Marketing", kategori: "ringan" },
  { nama_pekerjaan: "Manajer", kategori: "ringan" },
  { nama_pekerjaan: "Pilot", kategori: "sedang" },
  { nama_pekerjaan: "Sipir", kategori: "berat" },
  { nama_pekerjaan: "Pramugara", kategori: "sedang" },
  { nama_pekerjaan: "Bartender", kategori: "sedang" },
  { nama_pekerjaan: "Perawat Hewan", kategori: "ringan" },
  { nama_pekerjaan: "Teknisi Komputer", kategori: "ringan" },
  { nama_pekerjaan: "Supir", kategori: "sedang" },
  { nama_pekerjaan: "Satpam", kategori: "sedang" },
  { nama_pekerjaan: "Akuntan", kategori: "ringan" },
  { nama_pekerjaan: "Agen Asuransi", kategori: "ringan" },
  { nama_pekerjaan: "Pegawai Kantor Pos", kategori: "ringan" },
  { nama_pekerjaan: "Pegawai Imigrasi", kategori: "ringan" },
  { nama_pekerjaan: "Pelatih Olahraga", kategori: "ringan" },
  { nama_pekerjaan: "Karyawan Toko", kategori: "ringan" },
  { nama_pekerjaan: "Pegawai Keuangan", kategori: "ringan" },
  { nama_pekerjaan: "Pegawai Hotel", kategori: "sedang" },
  { nama_pekerjaan: "Pegawai Travel", kategori: "ringan" },
  { nama_pekerjaan: "Konsultan Keuangan", kategori: "ringan" },
  { nama_pekerjaan: "Pelukis", kategori: "ringan" },
  { nama_pekerjaan: "Koreografer", kategori: "sedang" },
  { nama_pekerjaan: "Pembawa Acara", kategori: "ringan" },
  { nama_pekerjaan: "Asisten Rumah Tangga", kategori: "sedang" },
  { nama_pekerjaan: "Juragan Kapal", kategori: "berat" },
  { nama_pekerjaan: "Pegawai Administrasi", kategori: "ringan" },
  { nama_pekerjaan: "Petugas Bank", kategori: "ringan" },
  { nama_pekerjaan: "Pelayan Restoran", kategori: "ringan" },
  { nama_pekerjaan: "Pekerja Konstruksi", kategori: "berat" },
  { nama_pekerjaan: "Petugas Parkir", kategori: "ringan" },
  { nama_pekerjaan: "Pegawai Jasa Pengiriman", kategori: "ringan" },
  { nama_pekerjaan: "Konsultan Bisnis", kategori: "ringan" },
  { nama_pekerjaan: "Penulis Naskah", kategori: "ringan" },
  { nama_pekerjaan: "Editor", kategori: "ringan" },
];
