import React, { useState } from "react";
import type { NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const Daftar: NextPage = () => {
  const router = useRouter();
  // usestate data diri berisi object name, email, password
  const [dataDiri, setDataDiri] = useState({
    name: "",
    username: "",
    password: "",
    konfirmasiPassword: "",
  });

  // handle change input
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setDataDiri({
      ...dataDiri,
      [e.target.name]: e.target.value,
    });
  };

  const handleDaftar = async (
    e: React.MouseEvent<HTMLButtonElement, MouseEvent>
  ) => {
    e.preventDefault();

    // cek apakah field telah diisi
    if (
      dataDiri.name === "" ||
      dataDiri.username === "" ||
      dataDiri.password === "" ||
      dataDiri.konfirmasiPassword === ""
    ) {
      toast.error("Semua field harus diisi");
      return;
    }

    // cek apakah password dan konfirmasi password sama
    if (dataDiri.password !== dataDiri.konfirmasiPassword) {
      toast.error("Password dan konfirmasi password tidak sama");
      return;
    }

    // buat request ke API untuk daftar
    const res = await fetch("/api/daftar", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(dataDiri),
    });

    // jika respon status 409, tampilkan pesan error
    if (res.status === 409) {
      toast.error("Username sudah digunakan");
      return;
    }

    // jika gagal, tampilkan pesan error
    if (!res.ok) {
      toast.error("Gagal mendaftar");
      return;
    }

    // jika berhasil, tampilkan pesan sukses
    toast.success("Akun anda berhasil di daftarkan, silahkan login!");
    // tunggu 3 detik kemudian alihkan ke halaman login
    setTimeout(() => {
      void router.push("/login");
    }, 3000);
  };

  return (
    <div className="flex h-screen w-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <Head>
        <title>Diabetes Assistant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer position="top-right" />
      <div className="flex w-[90%] flex-col items-center justify-between rounded-lg bg-white bg-opacity-95 py-4 shadow-md sm:w-[25%]">
        <div className="mb-2 text-center text-xl font-bold uppercase text-gray-700">
          Silahkan daftar
        </div>

        {/* jika belum punya akun, alihkan ke login */}
        <div className="mb-4 text-center text-sm text-gray-500">
          Sudah punya akun?{" "}
          <Link
            href="/login"
            className="text-blue-600 hover:text-blue-800 hover:underline"
          >
            Masuk
          </Link>
        </div>

        {/* input masuk dengan usename dan password */}
        <div className="mb-2 flex w-72 flex-col">
          <label
            htmlFor="Nama Lengkap"
            className="mb-1 text-sm font-medium text-gray-600"
          >
            Nama Lengkap
          </label>
          <input
            type="text"
            id="Nama Lengkap"
            name="name"
            className="rounded-md border border-gray-300 px-4 py-2 focus:border-blue-500 focus:outline-none"
            onChange={(e) => {
              handleChange(e);
            }}
          />
        </div>
        <div className="mb-2 flex w-72 flex-col">
          <label
            htmlFor="username"
            className="mb-1 text-sm font-medium text-gray-600"
          >
            Username
          </label>
          <input
            type="text"
            id="username"
            name="username"
            className="rounded-md border border-gray-300 px-4 py-2 focus:border-blue-500 focus:outline-none"
            onChange={(e) => {
              handleChange(e);
            }}
          />
        </div>
        <div className="mb-2 flex w-72 flex-col">
          <label
            htmlFor="password"
            className="mb-1 text-sm font-medium text-gray-600"
          >
            Password
          </label>
          <input
            type="password"
            id="password"
            name="password"
            className="rounded-md border border-gray-300 px-4 py-2 focus:border-blue-500 focus:outline-none"
            onChange={(e) => {
              handleChange(e);
            }}
          />
        </div>
        <div className="mb-2 flex w-72 flex-col">
          <label
            htmlFor="password"
            className="mb-1 text-sm font-medium text-gray-600"
          >
            Konfirmasi Password
          </label>
          <input
            type="password"
            id="password"
            name="konfirmasiPassword"
            className="rounded-md border border-gray-300 px-4 py-2 focus:border-blue-500 focus:outline-none"
            onChange={(e) => {
              handleChange(e);
            }}
          />
        </div>
        {/* tombol login */}
        <button
          onClick={(e) => void handleDaftar(e)}
          className="mt-2 mb-4 w-72 rounded bg-blue-600 px-6 py-2.5 font-medium leading-tight text-white shadow-md transition duration-150 ease-in-out hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-none"
        >
          Daftar
        </button>

        {/* pemisah dengan tulisan atau */}
        <div className="mb-4 mt-2 flex w-72 items-center justify-center">
          <div className="w-1/5 border-b md:w-1/4" />
          <div className="mx-2 text-xs font-medium uppercase text-gray-500">
            atau
          </div>
          <div className="w-1/5 border-b md:w-1/4" />
        </div>

        {/* masuk dengan akun google  */}
        <button
          onClick={() =>
            void signIn("google", {
              callbackUrl: "/panel",
            })
          }
          className="mb-4 w-72 rounded bg-red-600 px-6 py-2.5 font-medium leading-tight text-white shadow-md transition duration-150 ease-in-out hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-none"
        >
          Masuk dengan Google
        </button>
      </div>
    </div>
  );
};

export default Daftar;
