import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import MateriCard from "../components/MateriCard";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Belajar BISINDO</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {/* HEADING/NAVBAR LOGO ON THE LEFT, SIGN IN AND SIGN UP ON THE RIGHT */}
        <div className="flex w-full items-center justify-between p-4 sm:px-12">
          <div className="flex items-center gap-3">
            <img src="/logo.png" alt="logo" className="h-10 w-10" />
            <h1 className="text-2xl font-bold tracking-tight text-white sm:text-3xl">
              BISINDO
            </h1>
          </div>
          <div className="flex items-center gap-4">
            <Link href="/daftar">
              <div className="font-medium tracking-tight text-white">
                Daftar
              </div>
            </Link>
            <Link href="/login">
              <div className="rounded-full border-2 border-gray-200 p-1 px-4 font-medium tracking-tight text-white">
                Login
              </div>
            </Link>
          </div>
        </div>
        {/* landing page main text */}
        <div className="container flex flex-col items-center justify-center gap-4 px-4 py-8 sm:gap-6 sm:py-16 ">
          <h1 className="text-center text-2xl font-bold tracking-wider text-white sm:px-16 sm:text-5xl">
            Selamat datang di situs belajar Bahasa Isyarat Indonesia{" "}
            <span className="text-[hsl(280,100%,70%)]">BISINDO</span>
          </h1>
          <p className="px-6 text-center text-lg font-medium tracking-tight text-gray-300 sm:text-2xl">
            Silahkan pilih materi di bawah dan mulai belajar!
          </p>
        </div>
        <div className="flex flex-col gap-6 pb-8 sm:flex-row">
          {/* card with image and caption */}
          <MateriCard
            title="Abjad BISINDO"
            image="https://loremflickr.com/250/150/hand?random=1"
          />
          <MateriCard
            title="Kamus BISINDO"
            image="https://loremflickr.com/250/150/hand?random=2"
          />
          <MateriCard
            title="Kalimat Perkenalan"
            image="https://loremflickr.com/250/150/hand?random=3"
          />
        </div>
      </main>
    </>
  );
};

export default Home;
