import type { NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";

const Daftar: NextPage = () => {
  const Loading = () => (
    <div>
      <div
        className="modal fade fixed top-0 left-0 hidden h-full w-full overflow-y-auto overflow-x-hidden outline-none"
        id="staticBackdrop"
        data-bs-backdrop="static"
        data-bs-keyboard="false"
        tabIndex={-1}
        aria-labelledby="staticBackdropLabel"
        aria-hidden="true"
      >
        <div className="modal-dialog pointer-events-none relative flex w-auto justify-center">
          <div className="modal-content pointer-events-auto relative flex w-2/3 flex-col rounded-md border-none bg-white bg-clip-padding text-current shadow-lg outline-none">
            <div className="modal-header flex flex-shrink-0 items-center justify-between rounded-t-md p-4">
              <h5
                className="text-xl font-medium leading-normal text-gray-800"
                id="exampleModalLabel"
              >
                Loading...
              </h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  );

  return (
    <div className="flex h-screen w-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <Head>
        <title>Belajar BISINDO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Loading />
      <div className="flex w-80 flex-col items-center justify-between rounded-lg bg-white bg-opacity-95 shadow-md">
        <div className="mb-2 py-2 text-center text-xl font-bold text-gray-700">
          Silahkan login
        </div>
        {/* masuk dengan akun google  */}
        <button
          onClick={() =>
            void signIn("google", {
              callbackUrl: "/materi",
            })
          }
          className="mb-4 w-64 rounded bg-red-600 px-6 py-2.5 font-medium leading-tight text-white shadow-md transition duration-150 ease-in-out hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-none"
        >
          Masuk dengan Google
        </button>
      </div>
    </div>
  );
};

export default Daftar;
